/**
 * kdepa-api
 * КДЭПА CRUD API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.KdepaApi);
  }
}(this, function(expect, KdepaApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new KdepaApi.AssemblyDto();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('AssemblyDto', function() {
    it('should create an instance of AssemblyDto', function() {
      // uncomment below and update the code to test AssemblyDto
      //var instance = new KdepaApi.AssemblyDto();
      //expect(instance).to.be.a(KdepaApi.AssemblyDto);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new KdepaApi.AssemblyDto();
      //expect(instance).to.be();
    });

    it('should have the property valveId (base name: "valveId")', function() {
      // uncomment below and update the code to test the property valveId
      //var instance = new KdepaApi.AssemblyDto();
      //expect(instance).to.be();
    });

    it('should have the property valve (base name: "valve")', function() {
      // uncomment below and update the code to test the property valve
      //var instance = new KdepaApi.AssemblyDto();
      //expect(instance).to.be();
    });

    it('should have the property driveId (base name: "driveId")', function() {
      // uncomment below and update the code to test the property driveId
      //var instance = new KdepaApi.AssemblyDto();
      //expect(instance).to.be();
    });

    it('should have the property drive (base name: "drive")', function() {
      // uncomment below and update the code to test the property drive
      //var instance = new KdepaApi.AssemblyDto();
      //expect(instance).to.be();
    });

    it('should have the property motorId (base name: "motorId")', function() {
      // uncomment below and update the code to test the property motorId
      //var instance = new KdepaApi.AssemblyDto();
      //expect(instance).to.be();
    });

    it('should have the property motor (base name: "motor")', function() {
      // uncomment below and update the code to test the property motor
      //var instance = new KdepaApi.AssemblyDto();
      //expect(instance).to.be();
    });

    it('should have the property positionId (base name: "positionId")', function() {
      // uncomment below and update the code to test the property positionId
      //var instance = new KdepaApi.AssemblyDto();
      //expect(instance).to.be();
    });

    it('should have the property position (base name: "position")', function() {
      // uncomment below and update the code to test the property position
      //var instance = new KdepaApi.AssemblyDto();
      //expect(instance).to.be();
    });

    it('should have the property buildingDate (base name: "buildingDate")', function() {
      // uncomment below and update the code to test the property buildingDate
      //var instance = new KdepaApi.AssemblyDto();
      //expect(instance).to.be();
    });

  });

}));
