/**
 * kdepa-api
 * КДЭПА CRUD API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.KdepaApi);
  }
}(this, function(expect, KdepaApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new KdepaApi.AssembliesQueryFilterDto();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('AssembliesQueryFilterDto', function() {
    it('should create an instance of AssembliesQueryFilterDto', function() {
      // uncomment below and update the code to test AssembliesQueryFilterDto
      //var instance = new KdepaApi.AssembliesQueryFilterDto();
      //expect(instance).to.be.a(KdepaApi.AssembliesQueryFilterDto);
    });

    it('should have the property ids (base name: "ids")', function() {
      // uncomment below and update the code to test the property ids
      //var instance = new KdepaApi.AssembliesQueryFilterDto();
      //expect(instance).to.be();
    });

    it('should have the property positionIds (base name: "positionIds")', function() {
      // uncomment below and update the code to test the property positionIds
      //var instance = new KdepaApi.AssembliesQueryFilterDto();
      //expect(instance).to.be();
    });

    it('should have the property valveIds (base name: "valveIds")', function() {
      // uncomment below and update the code to test the property valveIds
      //var instance = new KdepaApi.AssembliesQueryFilterDto();
      //expect(instance).to.be();
    });

    it('should have the property driveIds (base name: "driveIds")', function() {
      // uncomment below and update the code to test the property driveIds
      //var instance = new KdepaApi.AssembliesQueryFilterDto();
      //expect(instance).to.be();
    });

    it('should have the property motorIds (base name: "motorIds")', function() {
      // uncomment below and update the code to test the property motorIds
      //var instance = new KdepaApi.AssembliesQueryFilterDto();
      //expect(instance).to.be();
    });

    it('should have the property dateFrom (base name: "dateFrom")', function() {
      // uncomment below and update the code to test the property dateFrom
      //var instance = new KdepaApi.AssembliesQueryFilterDto();
      //expect(instance).to.be();
    });

    it('should have the property dateTo (base name: "dateTo")', function() {
      // uncomment below and update the code to test the property dateTo
      //var instance = new KdepaApi.AssembliesQueryFilterDto();
      //expect(instance).to.be();
    });

    it('should have the property openTime (base name: "openTime")', function() {
      // uncomment below and update the code to test the property openTime
      //var instance = new KdepaApi.AssembliesQueryFilterDto();
      //expect(instance).to.be();
    });

    it('should have the property closeTime (base name: "closeTime")', function() {
      // uncomment below and update the code to test the property closeTime
      //var instance = new KdepaApi.AssembliesQueryFilterDto();
      //expect(instance).to.be();
    });

    it('should have the property isFastActing (base name: "isFastActing")', function() {
      // uncomment below and update the code to test the property isFastActing
      //var instance = new KdepaApi.AssembliesQueryFilterDto();
      //expect(instance).to.be();
    });

  });

}));
