/**
 * kdepa-api
 * КДЭПА CRUD API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import BlockDto from './BlockDto';
import BlocksQueryFilterDto from './BlocksQueryFilterDto';
import SortDto from './SortDto';

/**
 * The BlockDtoBlocksQueryFilterDtoPagedItemsDto model module.
 * @module model/BlockDtoBlocksQueryFilterDtoPagedItemsDto
 * @version 0.1.0
 */
class BlockDtoBlocksQueryFilterDtoPagedItemsDto {
    /**
     * Constructs a new <code>BlockDtoBlocksQueryFilterDtoPagedItemsDto</code>.
     * @alias module:model/BlockDtoBlocksQueryFilterDtoPagedItemsDto
     */
    constructor() { 
        
        BlockDtoBlocksQueryFilterDtoPagedItemsDto.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>BlockDtoBlocksQueryFilterDtoPagedItemsDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/BlockDtoBlocksQueryFilterDtoPagedItemsDto} obj Optional instance to populate.
     * @return {module:model/BlockDtoBlocksQueryFilterDtoPagedItemsDto} The populated <code>BlockDtoBlocksQueryFilterDtoPagedItemsDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BlockDtoBlocksQueryFilterDtoPagedItemsDto();

            if (data.hasOwnProperty('pageIndex')) {
                obj['pageIndex'] = ApiClient.convertToType(data['pageIndex'], 'Number');
            }
            if (data.hasOwnProperty('pageSize')) {
                obj['pageSize'] = ApiClient.convertToType(data['pageSize'], 'Number');
            }
            if (data.hasOwnProperty('totalItems')) {
                obj['totalItems'] = ApiClient.convertToType(data['totalItems'], 'Number');
            }
            if (data.hasOwnProperty('totalPages')) {
                obj['totalPages'] = ApiClient.convertToType(data['totalPages'], 'Number');
            }
            if (data.hasOwnProperty('items')) {
                obj['items'] = ApiClient.convertToType(data['items'], [BlockDto]);
            }
            if (data.hasOwnProperty('sort')) {
                obj['sort'] = SortDto.constructFromObject(data['sort']);
            }
            if (data.hasOwnProperty('filter')) {
                obj['filter'] = BlocksQueryFilterDto.constructFromObject(data['filter']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>BlockDtoBlocksQueryFilterDtoPagedItemsDto</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>BlockDtoBlocksQueryFilterDtoPagedItemsDto</code>.
     */
    static validateJSON(data) {
        if (data['items']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['items'])) {
                throw new Error("Expected the field `items` to be an array in the JSON data but got " + data['items']);
            }
            // validate the optional field `items` (array)
            for (const item of data['items']) {
                BlockDto.validateJSON(item);
            };
        }
        // validate the optional field `sort`
        if (data['sort']) { // data not null
          SortDto.validateJSON(data['sort']);
        }
        // validate the optional field `filter`
        if (data['filter']) { // data not null
          BlocksQueryFilterDto.validateJSON(data['filter']);
        }

        return true;
    }


}



/**
 * @member {Number} pageIndex
 */
BlockDtoBlocksQueryFilterDtoPagedItemsDto.prototype['pageIndex'] = undefined;

/**
 * @member {Number} pageSize
 */
BlockDtoBlocksQueryFilterDtoPagedItemsDto.prototype['pageSize'] = undefined;

/**
 * @member {Number} totalItems
 */
BlockDtoBlocksQueryFilterDtoPagedItemsDto.prototype['totalItems'] = undefined;

/**
 * @member {Number} totalPages
 */
BlockDtoBlocksQueryFilterDtoPagedItemsDto.prototype['totalPages'] = undefined;

/**
 * @member {Array.<module:model/BlockDto>} items
 */
BlockDtoBlocksQueryFilterDtoPagedItemsDto.prototype['items'] = undefined;

/**
 * @member {module:model/SortDto} sort
 */
BlockDtoBlocksQueryFilterDtoPagedItemsDto.prototype['sort'] = undefined;

/**
 * @member {module:model/BlocksQueryFilterDto} filter
 */
BlockDtoBlocksQueryFilterDtoPagedItemsDto.prototype['filter'] = undefined;






export default BlockDtoBlocksQueryFilterDtoPagedItemsDto;

