/**
 * kdepa-api
 * КДЭПА CRUD API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ChartType from './ChartType';

/**
 * The ChartFilterDto model module.
 * @module model/ChartFilterDto
 * @version 0.1.0
 */
class ChartFilterDto {
    /**
     * Constructs a new <code>ChartFilterDto</code>.
     * @alias module:model/ChartFilterDto
     */
    constructor() { 
        
        ChartFilterDto.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ChartFilterDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ChartFilterDto} obj Optional instance to populate.
     * @return {module:model/ChartFilterDto} The populated <code>ChartFilterDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ChartFilterDto();

            if (data.hasOwnProperty('type')) {
                obj['type'] = ChartType.constructFromObject(data['type']);
            }
            if (data.hasOwnProperty('from')) {
                obj['from'] = ApiClient.convertToType(data['from'], 'Number');
            }
            if (data.hasOwnProperty('to')) {
                obj['to'] = ApiClient.convertToType(data['to'], 'Number');
            }
            if (data.hasOwnProperty('samples')) {
                obj['samples'] = ApiClient.convertToType(data['samples'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ChartFilterDto</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ChartFilterDto</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * @member {module:model/ChartType} type
 */
ChartFilterDto.prototype['type'] = undefined;

/**
 * @member {Number} from
 */
ChartFilterDto.prototype['from'] = undefined;

/**
 * @member {Number} to
 */
ChartFilterDto.prototype['to'] = undefined;

/**
 * @member {Number} samples
 */
ChartFilterDto.prototype['samples'] = undefined;






export default ChartFilterDto;

