/**
 * kdepa-api
 * КДЭПА CRUD API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ChartPoint model module.
 * @module model/ChartPoint
 * @version 0.1.0
 */
class ChartPoint {
    /**
     * Constructs a new <code>ChartPoint</code>.
     * @alias module:model/ChartPoint
     */
    constructor() { 
        
        ChartPoint.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ChartPoint</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ChartPoint} obj Optional instance to populate.
     * @return {module:model/ChartPoint} The populated <code>ChartPoint</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ChartPoint();

            if (data.hasOwnProperty('x')) {
                obj['x'] = ApiClient.convertToType(data['x'], 'Number');
            }
            if (data.hasOwnProperty('y')) {
                obj['y'] = ApiClient.convertToType(data['y'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ChartPoint</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ChartPoint</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * @member {Number} x
 */
ChartPoint.prototype['x'] = undefined;

/**
 * @member {Number} y
 */
ChartPoint.prototype['y'] = undefined;






export default ChartPoint;

