/**
 * kdepa-api
 * КДЭПА CRUD API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CreateOrUpdateValveMarkRequest model module.
 * @module model/CreateOrUpdateValveMarkRequest
 * @version 0.1.0
 */
class CreateOrUpdateValveMarkRequest {
    /**
     * Constructs a new <code>CreateOrUpdateValveMarkRequest</code>.
     * @alias module:model/CreateOrUpdateValveMarkRequest
     */
    constructor() { 
        
        CreateOrUpdateValveMarkRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CreateOrUpdateValveMarkRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreateOrUpdateValveMarkRequest} obj Optional instance to populate.
     * @return {module:model/CreateOrUpdateValveMarkRequest} The populated <code>CreateOrUpdateValveMarkRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateOrUpdateValveMarkRequest();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('valveTypeId')) {
                obj['valveTypeId'] = ApiClient.convertToType(data['valveTypeId'], 'Number');
            }
            if (data.hasOwnProperty('dn')) {
                obj['dn'] = ApiClient.convertToType(data['dn'], 'Number');
            }
            if (data.hasOwnProperty('pn')) {
                obj['pn'] = ApiClient.convertToType(data['pn'], 'Number');
            }
            if (data.hasOwnProperty('tn')) {
                obj['tn'] = ApiClient.convertToType(data['tn'], 'Number');
            }
            if (data.hasOwnProperty('movementTimeMin')) {
                obj['movementTimeMin'] = ApiClient.convertToType(data['movementTimeMin'], 'Number');
            }
            if (data.hasOwnProperty('movementTimeMax')) {
                obj['movementTimeMax'] = ApiClient.convertToType(data['movementTimeMax'], 'Number');
            }
            if (data.hasOwnProperty('modification')) {
                obj['modification'] = ApiClient.convertToType(data['modification'], 'String');
            }
            if (data.hasOwnProperty('serviceLife')) {
                obj['serviceLife'] = ApiClient.convertToType(data['serviceLife'], 'Number');
            }
            if (data.hasOwnProperty('assignedResource')) {
                obj['assignedResource'] = ApiClient.convertToType(data['assignedResource'], 'Number');
            }
            if (data.hasOwnProperty('timeToFailure')) {
                obj['timeToFailure'] = ApiClient.convertToType(data['timeToFailure'], 'Number');
            }
            if (data.hasOwnProperty('probabilityOfFailure')) {
                obj['probabilityOfFailure'] = ApiClient.convertToType(data['probabilityOfFailure'], 'Number');
            }
            if (data.hasOwnProperty('technicalUseCoeff')) {
                obj['technicalUseCoeff'] = ApiClient.convertToType(data['technicalUseCoeff'], 'Number');
            }
            if (data.hasOwnProperty('availabilityFactor')) {
                obj['availabilityFactor'] = ApiClient.convertToType(data['availabilityFactor'], 'Number');
            }
            if (data.hasOwnProperty('safetyClassId')) {
                obj['safetyClassId'] = ApiClient.convertToType(data['safetyClassId'], 'Number');
            }
            if (data.hasOwnProperty('equipmentGroupId')) {
                obj['equipmentGroupId'] = ApiClient.convertToType(data['equipmentGroupId'], 'Number');
            }
            if (data.hasOwnProperty('seismicCategoryId')) {
                obj['seismicCategoryId'] = ApiClient.convertToType(data['seismicCategoryId'], 'Number');
            }
            if (data.hasOwnProperty('usingClassId')) {
                obj['usingClassId'] = ApiClient.convertToType(data['usingClassId'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CreateOrUpdateValveMarkRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CreateOrUpdateValveMarkRequest</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['modification'] && !(typeof data['modification'] === 'string' || data['modification'] instanceof String)) {
            throw new Error("Expected the field `modification` to be a primitive type in the JSON string but got " + data['modification']);
        }

        return true;
    }


}



/**
 * @member {String} name
 */
CreateOrUpdateValveMarkRequest.prototype['name'] = undefined;

/**
 * @member {Number} valveTypeId
 */
CreateOrUpdateValveMarkRequest.prototype['valveTypeId'] = undefined;

/**
 * @member {Number} dn
 */
CreateOrUpdateValveMarkRequest.prototype['dn'] = undefined;

/**
 * @member {Number} pn
 */
CreateOrUpdateValveMarkRequest.prototype['pn'] = undefined;

/**
 * @member {Number} tn
 */
CreateOrUpdateValveMarkRequest.prototype['tn'] = undefined;

/**
 * @member {Number} movementTimeMin
 */
CreateOrUpdateValveMarkRequest.prototype['movementTimeMin'] = undefined;

/**
 * @member {Number} movementTimeMax
 */
CreateOrUpdateValveMarkRequest.prototype['movementTimeMax'] = undefined;

/**
 * @member {String} modification
 */
CreateOrUpdateValveMarkRequest.prototype['modification'] = undefined;

/**
 * @member {Number} serviceLife
 */
CreateOrUpdateValveMarkRequest.prototype['serviceLife'] = undefined;

/**
 * @member {Number} assignedResource
 */
CreateOrUpdateValveMarkRequest.prototype['assignedResource'] = undefined;

/**
 * @member {Number} timeToFailure
 */
CreateOrUpdateValveMarkRequest.prototype['timeToFailure'] = undefined;

/**
 * @member {Number} probabilityOfFailure
 */
CreateOrUpdateValveMarkRequest.prototype['probabilityOfFailure'] = undefined;

/**
 * @member {Number} technicalUseCoeff
 */
CreateOrUpdateValveMarkRequest.prototype['technicalUseCoeff'] = undefined;

/**
 * @member {Number} availabilityFactor
 */
CreateOrUpdateValveMarkRequest.prototype['availabilityFactor'] = undefined;

/**
 * @member {Number} safetyClassId
 */
CreateOrUpdateValveMarkRequest.prototype['safetyClassId'] = undefined;

/**
 * @member {Number} equipmentGroupId
 */
CreateOrUpdateValveMarkRequest.prototype['equipmentGroupId'] = undefined;

/**
 * @member {Number} seismicCategoryId
 */
CreateOrUpdateValveMarkRequest.prototype['seismicCategoryId'] = undefined;

/**
 * @member {Number} usingClassId
 */
CreateOrUpdateValveMarkRequest.prototype['usingClassId'] = undefined;






export default CreateOrUpdateValveMarkRequest;

