/**
 * kdepa-api
 * КДЭПА CRUD API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CreateChannelSubRequest from './CreateChannelSubRequest';

/**
 * The CreateSurveyRequest model module.
 * @module model/CreateSurveyRequest
 * @version 0.1.0
 */
class CreateSurveyRequest {
    /**
     * Constructs a new <code>CreateSurveyRequest</code>.
     * @alias module:model/CreateSurveyRequest
     */
    constructor() { 
        
        CreateSurveyRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CreateSurveyRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreateSurveyRequest} obj Optional instance to populate.
     * @return {module:model/CreateSurveyRequest} The populated <code>CreateSurveyRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateSurveyRequest();

            if (data.hasOwnProperty('positionId')) {
                obj['positionId'] = ApiClient.convertToType(data['positionId'], 'Number');
            }
            if (data.hasOwnProperty('dateTime')) {
                obj['dateTime'] = ApiClient.convertToType(data['dateTime'], 'Date');
            }
            if (data.hasOwnProperty('resistance')) {
                obj['resistance'] = ApiClient.convertToType(data['resistance'], 'Number');
            }
            if (data.hasOwnProperty('mvo')) {
                obj['mvo'] = ApiClient.convertToType(data['mvo'], 'Number');
            }
            if (data.hasOwnProperty('mvz')) {
                obj['mvz'] = ApiClient.convertToType(data['mvz'], 'Number');
            }
            if (data.hasOwnProperty('direction')) {
                obj['direction'] = ApiClient.convertToType(data['direction'], 'String');
            }
            if (data.hasOwnProperty('comment')) {
                obj['comment'] = ApiClient.convertToType(data['comment'], 'String');
            }
            if (data.hasOwnProperty('channels')) {
                obj['channels'] = ApiClient.convertToType(data['channels'], [CreateChannelSubRequest]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CreateSurveyRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CreateSurveyRequest</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['direction'] && !(typeof data['direction'] === 'string' || data['direction'] instanceof String)) {
            throw new Error("Expected the field `direction` to be a primitive type in the JSON string but got " + data['direction']);
        }
        // ensure the json data is a string
        if (data['comment'] && !(typeof data['comment'] === 'string' || data['comment'] instanceof String)) {
            throw new Error("Expected the field `comment` to be a primitive type in the JSON string but got " + data['comment']);
        }
        if (data['channels']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['channels'])) {
                throw new Error("Expected the field `channels` to be an array in the JSON data but got " + data['channels']);
            }
            // validate the optional field `channels` (array)
            for (const item of data['channels']) {
                CreateChannelSubRequest.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * @member {Number} positionId
 */
CreateSurveyRequest.prototype['positionId'] = undefined;

/**
 * @member {Date} dateTime
 */
CreateSurveyRequest.prototype['dateTime'] = undefined;

/**
 * @member {Number} resistance
 */
CreateSurveyRequest.prototype['resistance'] = undefined;

/**
 * @member {Number} mvo
 */
CreateSurveyRequest.prototype['mvo'] = undefined;

/**
 * @member {Number} mvz
 */
CreateSurveyRequest.prototype['mvz'] = undefined;

/**
 * @member {String} direction
 */
CreateSurveyRequest.prototype['direction'] = undefined;

/**
 * @member {String} comment
 */
CreateSurveyRequest.prototype['comment'] = undefined;

/**
 * @member {Array.<module:model/CreateChannelSubRequest>} channels
 */
CreateSurveyRequest.prototype['channels'] = undefined;






export default CreateSurveyRequest;

