/**
 * kdepa-api
 * КДЭПА CRUD API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The DriveDto model module.
 * @module model/DriveDto
 * @version 0.1.0
 */
class DriveDto {
    /**
     * Constructs a new <code>DriveDto</code>.
     * @alias module:model/DriveDto
     */
    constructor() { 
        
        DriveDto.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>DriveDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DriveDto} obj Optional instance to populate.
     * @return {module:model/DriveDto} The populated <code>DriveDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DriveDto();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('markId')) {
                obj['markId'] = ApiClient.convertToType(data['markId'], 'Number');
            }
            if (data.hasOwnProperty('mark')) {
                obj['mark'] = ApiClient.convertToType(data['mark'], 'String');
            }
            if (data.hasOwnProperty('factoryId')) {
                obj['factoryId'] = ApiClient.convertToType(data['factoryId'], 'Number');
            }
            if (data.hasOwnProperty('factory')) {
                obj['factory'] = ApiClient.convertToType(data['factory'], 'String');
            }
            if (data.hasOwnProperty('serialNumber')) {
                obj['serialNumber'] = ApiClient.convertToType(data['serialNumber'], 'String');
            }
            if (data.hasOwnProperty('madeDate')) {
                obj['madeDate'] = ApiClient.convertToType(data['madeDate'], 'Date');
            }
            if (data.hasOwnProperty('inUseDate')) {
                obj['inUseDate'] = ApiClient.convertToType(data['inUseDate'], 'Date');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>DriveDto</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>DriveDto</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['mark'] && !(typeof data['mark'] === 'string' || data['mark'] instanceof String)) {
            throw new Error("Expected the field `mark` to be a primitive type in the JSON string but got " + data['mark']);
        }
        // ensure the json data is a string
        if (data['factory'] && !(typeof data['factory'] === 'string' || data['factory'] instanceof String)) {
            throw new Error("Expected the field `factory` to be a primitive type in the JSON string but got " + data['factory']);
        }
        // ensure the json data is a string
        if (data['serialNumber'] && !(typeof data['serialNumber'] === 'string' || data['serialNumber'] instanceof String)) {
            throw new Error("Expected the field `serialNumber` to be a primitive type in the JSON string but got " + data['serialNumber']);
        }

        return true;
    }


}



/**
 * @member {Number} id
 */
DriveDto.prototype['id'] = undefined;

/**
 * @member {Number} markId
 */
DriveDto.prototype['markId'] = undefined;

/**
 * @member {String} mark
 */
DriveDto.prototype['mark'] = undefined;

/**
 * @member {Number} factoryId
 */
DriveDto.prototype['factoryId'] = undefined;

/**
 * @member {String} factory
 */
DriveDto.prototype['factory'] = undefined;

/**
 * @member {String} serialNumber
 */
DriveDto.prototype['serialNumber'] = undefined;

/**
 * @member {Date} madeDate
 */
DriveDto.prototype['madeDate'] = undefined;

/**
 * @member {Date} inUseDate
 */
DriveDto.prototype['inUseDate'] = undefined;






export default DriveDto;

