/**
 * kdepa-api
 * КДЭПА CRUD API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PositionsQueryFilterDto model module.
 * @module model/PositionsQueryFilterDto
 * @version 0.1.0
 */
class PositionsQueryFilterDto {
    /**
     * Constructs a new <code>PositionsQueryFilterDto</code>.
     * @alias module:model/PositionsQueryFilterDto
     */
    constructor() { 
        
        PositionsQueryFilterDto.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PositionsQueryFilterDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PositionsQueryFilterDto} obj Optional instance to populate.
     * @return {module:model/PositionsQueryFilterDto} The populated <code>PositionsQueryFilterDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PositionsQueryFilterDto();

            if (data.hasOwnProperty('ids')) {
                obj['ids'] = ApiClient.convertToType(data['ids'], ['Number']);
            }
            if (data.hasOwnProperty('blockIds')) {
                obj['blockIds'] = ApiClient.convertToType(data['blockIds'], ['Number']);
            }
            if (data.hasOwnProperty('systemIds')) {
                obj['systemIds'] = ApiClient.convertToType(data['systemIds'], ['Number']);
            }
            if (data.hasOwnProperty('shopIds')) {
                obj['shopIds'] = ApiClient.convertToType(data['shopIds'], ['Number']);
            }
            if (data.hasOwnProperty('safetyClassIds')) {
                obj['safetyClassIds'] = ApiClient.convertToType(data['safetyClassIds'], ['Number']);
            }
            if (data.hasOwnProperty('cabinetIds')) {
                obj['cabinetIds'] = ApiClient.convertToType(data['cabinetIds'], ['Number']);
            }
            if (data.hasOwnProperty('mediumIds')) {
                obj['mediumIds'] = ApiClient.convertToType(data['mediumIds'], ['Number']);
            }
            if (data.hasOwnProperty('nameSearchString')) {
                obj['nameSearchString'] = ApiClient.convertToType(data['nameSearchString'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PositionsQueryFilterDto</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PositionsQueryFilterDto</code>.
     */
    static validateJSON(data) {
        // ensure the json data is an array
        if (!Array.isArray(data['ids'])) {
            throw new Error("Expected the field `ids` to be an array in the JSON data but got " + data['ids']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['blockIds'])) {
            throw new Error("Expected the field `blockIds` to be an array in the JSON data but got " + data['blockIds']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['systemIds'])) {
            throw new Error("Expected the field `systemIds` to be an array in the JSON data but got " + data['systemIds']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['shopIds'])) {
            throw new Error("Expected the field `shopIds` to be an array in the JSON data but got " + data['shopIds']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['safetyClassIds'])) {
            throw new Error("Expected the field `safetyClassIds` to be an array in the JSON data but got " + data['safetyClassIds']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['cabinetIds'])) {
            throw new Error("Expected the field `cabinetIds` to be an array in the JSON data but got " + data['cabinetIds']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['mediumIds'])) {
            throw new Error("Expected the field `mediumIds` to be an array in the JSON data but got " + data['mediumIds']);
        }
        // ensure the json data is a string
        if (data['nameSearchString'] && !(typeof data['nameSearchString'] === 'string' || data['nameSearchString'] instanceof String)) {
            throw new Error("Expected the field `nameSearchString` to be a primitive type in the JSON string but got " + data['nameSearchString']);
        }

        return true;
    }


}



/**
 * @member {Array.<Number>} ids
 */
PositionsQueryFilterDto.prototype['ids'] = undefined;

/**
 * @member {Array.<Number>} blockIds
 */
PositionsQueryFilterDto.prototype['blockIds'] = undefined;

/**
 * @member {Array.<Number>} systemIds
 */
PositionsQueryFilterDto.prototype['systemIds'] = undefined;

/**
 * @member {Array.<Number>} shopIds
 */
PositionsQueryFilterDto.prototype['shopIds'] = undefined;

/**
 * @member {Array.<Number>} safetyClassIds
 */
PositionsQueryFilterDto.prototype['safetyClassIds'] = undefined;

/**
 * @member {Array.<Number>} cabinetIds
 */
PositionsQueryFilterDto.prototype['cabinetIds'] = undefined;

/**
 * @member {Array.<Number>} mediumIds
 */
PositionsQueryFilterDto.prototype['mediumIds'] = undefined;

/**
 * @member {String} nameSearchString
 */
PositionsQueryFilterDto.prototype['nameSearchString'] = undefined;






export default PositionsQueryFilterDto;

