/**
 * kdepa-api-middleware
 * КДЭПА CRUD API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import SortDto from './SortDto';
import StationDto from './StationDto';

/**
 * The StationDtoPaginatedItemsDto model module.
 * @module model/StationDtoPaginatedItemsDto
 * @version 0.1.0
 */
class StationDtoPaginatedItemsDto {
    /**
     * Constructs a new <code>StationDtoPaginatedItemsDto</code>.
     * @alias module:model/StationDtoPaginatedItemsDto
     */
    constructor() { 
        
        StationDtoPaginatedItemsDto.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>StationDtoPaginatedItemsDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/StationDtoPaginatedItemsDto} obj Optional instance to populate.
     * @return {module:model/StationDtoPaginatedItemsDto} The populated <code>StationDtoPaginatedItemsDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new StationDtoPaginatedItemsDto();

            if (data.hasOwnProperty('pageIndex')) {
                obj['pageIndex'] = ApiClient.convertToType(data['pageIndex'], 'Number');
            }
            if (data.hasOwnProperty('totalPages')) {
                obj['totalPages'] = ApiClient.convertToType(data['totalPages'], 'Number');
            }
            if (data.hasOwnProperty('itemsPerPage')) {
                obj['itemsPerPage'] = ApiClient.convertToType(data['itemsPerPage'], 'Number');
            }
            if (data.hasOwnProperty('items')) {
                obj['items'] = ApiClient.convertToType(data['items'], [StationDto]);
            }
            if (data.hasOwnProperty('sort')) {
                obj['sort'] = SortDto.constructFromObject(data['sort']);
            }
            if (data.hasOwnProperty('filter')) {
                obj['filter'] = ApiClient.convertToType(data['filter'], Object);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>StationDtoPaginatedItemsDto</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>StationDtoPaginatedItemsDto</code>.
     */
    static validateJSON(data) {
        if (data['items']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['items'])) {
                throw new Error("Expected the field `items` to be an array in the JSON data but got " + data['items']);
            }
            // validate the optional field `items` (array)
            for (const item of data['items']) {
                StationDto.validateJSON(item);
            };
        }
        // validate the optional field `sort`
        if (data['sort']) { // data not null
          SortDto.validateJSON(data['sort']);
        }

        return true;
    }


}



/**
 * @member {Number} pageIndex
 */
StationDtoPaginatedItemsDto.prototype['pageIndex'] = undefined;

/**
 * @member {Number} totalPages
 */
StationDtoPaginatedItemsDto.prototype['totalPages'] = undefined;

/**
 * @member {Number} itemsPerPage
 */
StationDtoPaginatedItemsDto.prototype['itemsPerPage'] = undefined;

/**
 * @member {Array.<module:model/StationDto>} items
 */
StationDtoPaginatedItemsDto.prototype['items'] = undefined;

/**
 * @member {module:model/SortDto} sort
 */
StationDtoPaginatedItemsDto.prototype['sort'] = undefined;

/**
 * @member {Object} filter
 */
StationDtoPaginatedItemsDto.prototype['filter'] = undefined;






export default StationDtoPaginatedItemsDto;

