/**
 * kdepa-api
 * КДЭПА CRUD API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ChannelDto from './ChannelDto';
import SlicingDto from './SlicingDto';
import TimeSpan from './TimeSpan';

/**
 * The SurveyDto model module.
 * @module model/SurveyDto
 * @version 0.1.0
 */
class SurveyDto {
    /**
     * Constructs a new <code>SurveyDto</code>.
     * @alias module:model/SurveyDto
     */
    constructor() { 
        
        SurveyDto.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SurveyDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SurveyDto} obj Optional instance to populate.
     * @return {module:model/SurveyDto} The populated <code>SurveyDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SurveyDto();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('assemblyId')) {
                obj['assemblyId'] = ApiClient.convertToType(data['assemblyId'], 'Number');
            }
            if (data.hasOwnProperty('dateTime')) {
                obj['dateTime'] = ApiClient.convertToType(data['dateTime'], 'Date');
            }
            if (data.hasOwnProperty('resistance')) {
                obj['resistance'] = ApiClient.convertToType(data['resistance'], 'Number');
            }
            if (data.hasOwnProperty('mvo')) {
                obj['mvo'] = ApiClient.convertToType(data['mvo'], 'Number');
            }
            if (data.hasOwnProperty('mvz')) {
                obj['mvz'] = ApiClient.convertToType(data['mvz'], 'Number');
            }
            if (data.hasOwnProperty('direction')) {
                obj['direction'] = ApiClient.convertToType(data['direction'], 'String');
            }
            if (data.hasOwnProperty('comment')) {
                obj['comment'] = ApiClient.convertToType(data['comment'], 'String');
            }
            if (data.hasOwnProperty('channels')) {
                obj['channels'] = ApiClient.convertToType(data['channels'], [ChannelDto]);
            }
            if (data.hasOwnProperty('synched')) {
                obj['synched'] = ApiClient.convertToType(data['synched'], 'Boolean');
            }
            if (data.hasOwnProperty('sliced')) {
                obj['sliced'] = ApiClient.convertToType(data['sliced'], 'Boolean');
            }
            if (data.hasOwnProperty('analyzed')) {
                obj['analyzed'] = ApiClient.convertToType(data['analyzed'], 'Boolean');
            }
            if (data.hasOwnProperty('length')) {
                obj['length'] = TimeSpan.constructFromObject(data['length']);
            }
            if (data.hasOwnProperty('slicing')) {
                obj['slicing'] = SlicingDto.constructFromObject(data['slicing']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SurveyDto</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SurveyDto</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['direction'] && !(typeof data['direction'] === 'string' || data['direction'] instanceof String)) {
            throw new Error("Expected the field `direction` to be a primitive type in the JSON string but got " + data['direction']);
        }
        // ensure the json data is a string
        if (data['comment'] && !(typeof data['comment'] === 'string' || data['comment'] instanceof String)) {
            throw new Error("Expected the field `comment` to be a primitive type in the JSON string but got " + data['comment']);
        }
        if (data['channels']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['channels'])) {
                throw new Error("Expected the field `channels` to be an array in the JSON data but got " + data['channels']);
            }
            // validate the optional field `channels` (array)
            for (const item of data['channels']) {
                ChannelDto.validateJSON(item);
            };
        }
        // validate the optional field `length`
        if (data['length']) { // data not null
          TimeSpan.validateJSON(data['length']);
        }
        // validate the optional field `slicing`
        if (data['slicing']) { // data not null
          SlicingDto.validateJSON(data['slicing']);
        }

        return true;
    }


}



/**
 * @member {Number} id
 */
SurveyDto.prototype['id'] = undefined;

/**
 * @member {Number} assemblyId
 */
SurveyDto.prototype['assemblyId'] = undefined;

/**
 * @member {Date} dateTime
 */
SurveyDto.prototype['dateTime'] = undefined;

/**
 * @member {Number} resistance
 */
SurveyDto.prototype['resistance'] = undefined;

/**
 * @member {Number} mvo
 */
SurveyDto.prototype['mvo'] = undefined;

/**
 * @member {Number} mvz
 */
SurveyDto.prototype['mvz'] = undefined;

/**
 * @member {String} direction
 */
SurveyDto.prototype['direction'] = undefined;

/**
 * @member {String} comment
 */
SurveyDto.prototype['comment'] = undefined;

/**
 * @member {Array.<module:model/ChannelDto>} channels
 */
SurveyDto.prototype['channels'] = undefined;

/**
 * @member {Boolean} synched
 */
SurveyDto.prototype['synched'] = undefined;

/**
 * @member {Boolean} sliced
 */
SurveyDto.prototype['sliced'] = undefined;

/**
 * @member {Boolean} analyzed
 */
SurveyDto.prototype['analyzed'] = undefined;

/**
 * @member {module:model/TimeSpan} length
 */
SurveyDto.prototype['length'] = undefined;

/**
 * @member {module:model/SlicingDto} slicing
 */
SurveyDto.prototype['slicing'] = undefined;






export default SurveyDto;

