/**
 * kdepa-api
 * КДЭПА CRUD API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import TripleParamDto from './TripleParamDto';

/**
 * The TripleParamRowDto model module.
 * @module model/TripleParamRowDto
 * @version 0.1.0
 */
class TripleParamRowDto {
    /**
     * Constructs a new <code>TripleParamRowDto</code>.
     * @alias module:model/TripleParamRowDto
     */
    constructor() { 
        
        TripleParamRowDto.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>TripleParamRowDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TripleParamRowDto} obj Optional instance to populate.
     * @return {module:model/TripleParamRowDto} The populated <code>TripleParamRowDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TripleParamRowDto();

            if (data.hasOwnProperty('parameter')) {
                obj['parameter'] = TripleParamDto.constructFromObject(data['parameter']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>TripleParamRowDto</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>TripleParamRowDto</code>.
     */
    static validateJSON(data) {
        // validate the optional field `parameter`
        if (data['parameter']) { // data not null
          TripleParamDto.validateJSON(data['parameter']);
        }

        return true;
    }


}



/**
 * @member {module:model/TripleParamDto} parameter
 */
TripleParamRowDto.prototype['parameter'] = undefined;






export default TripleParamRowDto;

