/**
 * kdepa-api
 * КДЭПА CRUD API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import AssemblyDto from '../model/AssemblyDto';
import AssemblyDtoAssembliesQueryFilterDtoPagedItemsDto from '../model/AssemblyDtoAssembliesQueryFilterDtoPagedItemsDto';
import CreateOrUpdateAssemblyRequest from '../model/CreateOrUpdateAssemblyRequest';

/**
* Assemblies service.
* @module api/AssembliesApi
* @version 0.1.0
*/
export default class AssembliesApi {

    /**
    * Constructs a new AssembliesApi. 
    * @alias module:api/AssembliesApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * Получить пагинированный список Сборок
     * @param {Object} opts Optional parameters
     * @param {Number} [pageSize = 10)] 
     * @param {Number} [pageIndex = 0)] 
     * @param {String} [sortBy] 
     * @param {Boolean} [ascending] 
     * @param {Array.<Number>} [ids] 
     * @param {Array.<Number>} [positionIds] 
     * @param {Array.<Number>} [valveIds] 
     * @param {Array.<Number>} [driveIds] 
     * @param {Array.<Number>} [motorIds] 
     * @param {Date} [dateFrom] 
     * @param {Date} [dateTo] 
     * @param {Number} [openTime] 
     * @param {Number} [closeTime] 
     * @param {Boolean} [isFastActing] 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/AssemblyDtoAssembliesQueryFilterDtoPagedItemsDto} and HTTP response
     */
    assembliesGetWithHttpInfo(opts) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'pageSize': opts['pageSize'],
        'pageIndex': opts['pageIndex'],
        'SortBy': opts['sortBy'],
        'Ascending': opts['ascending'],
        'Ids': this.apiClient.buildCollectionParam(opts['ids'], 'multi'),
        'PositionIds': this.apiClient.buildCollectionParam(opts['positionIds'], 'multi'),
        'ValveIds': this.apiClient.buildCollectionParam(opts['valveIds'], 'multi'),
        'DriveIds': this.apiClient.buildCollectionParam(opts['driveIds'], 'multi'),
        'MotorIds': this.apiClient.buildCollectionParam(opts['motorIds'], 'multi'),
        'DateFrom': opts['dateFrom'],
        'DateTo': opts['dateTo'],
        'OpenTime': opts['openTime'],
        'CloseTime': opts['closeTime'],
        'IsFastActing': opts['isFastActing']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['text/plain', 'application/json', 'text/json'];
      let returnType = AssemblyDtoAssembliesQueryFilterDtoPagedItemsDto;
      return this.apiClient.callApi(
        '/Assemblies', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Получить пагинированный список Сборок
     * @param {Object} opts Optional parameters
     * @param {Number} opts.pageSize  (default to 10)
     * @param {Number} opts.pageIndex  (default to 0)
     * @param {String} opts.sortBy 
     * @param {Boolean} opts.ascending 
     * @param {Array.<Number>} opts.ids 
     * @param {Array.<Number>} opts.positionIds 
     * @param {Array.<Number>} opts.valveIds 
     * @param {Array.<Number>} opts.driveIds 
     * @param {Array.<Number>} opts.motorIds 
     * @param {Date} opts.dateFrom 
     * @param {Date} opts.dateTo 
     * @param {Number} opts.openTime 
     * @param {Number} opts.closeTime 
     * @param {Boolean} opts.isFastActing 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/AssemblyDtoAssembliesQueryFilterDtoPagedItemsDto}
     */
    assembliesGet(opts) {
      return this.assembliesGetWithHttpInfo(opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Удалить Сборку
     * @param {Number} id 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link String} and HTTP response
     */
    assembliesIdDeleteWithHttpInfo(id) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling assembliesIdDelete");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['text/plain', 'application/json', 'text/json'];
      let returnType = 'String';
      return this.apiClient.callApi(
        '/Assemblies/{id}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Удалить Сборку
     * @param {Number} id 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link String}
     */
    assembliesIdDelete(id) {
      return this.assembliesIdDeleteWithHttpInfo(id)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Получить Сборку по id
     * @param {Number} id 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/AssemblyDto} and HTTP response
     */
    assembliesIdGetWithHttpInfo(id) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling assembliesIdGet");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['text/plain', 'application/json', 'text/json'];
      let returnType = AssemblyDto;
      return this.apiClient.callApi(
        '/Assemblies/{id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Получить Сборку по id
     * @param {Number} id 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/AssemblyDto}
     */
    assembliesIdGet(id) {
      return this.assembliesIdGetWithHttpInfo(id)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Обновить Сборку
     * @param {Number} id 
     * @param {Object} opts Optional parameters
     * @param {module:model/CreateOrUpdateAssemblyRequest} [createOrUpdateAssemblyRequest] 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/AssemblyDto} and HTTP response
     */
    assembliesIdPutWithHttpInfo(id, opts) {
      opts = opts || {};
      let postBody = opts['createOrUpdateAssemblyRequest'];
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling assembliesIdPut");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json', 'text/json', 'application/*+json'];
      let accepts = ['text/plain', 'application/json', 'text/json'];
      let returnType = AssemblyDto;
      return this.apiClient.callApi(
        '/Assemblies/{id}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Обновить Сборку
     * @param {Number} id 
     * @param {Object} opts Optional parameters
     * @param {module:model/CreateOrUpdateAssemblyRequest} opts.createOrUpdateAssemblyRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/AssemblyDto}
     */
    assembliesIdPut(id, opts) {
      return this.assembliesIdPutWithHttpInfo(id, opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Создать Сборку
     * @param {Object} opts Optional parameters
     * @param {module:model/CreateOrUpdateAssemblyRequest} [createOrUpdateAssemblyRequest] 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/AssemblyDto} and HTTP response
     */
    assembliesPostWithHttpInfo(opts) {
      opts = opts || {};
      let postBody = opts['createOrUpdateAssemblyRequest'];

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json', 'text/json', 'application/*+json'];
      let accepts = ['text/plain', 'application/json', 'text/json'];
      let returnType = AssemblyDto;
      return this.apiClient.callApi(
        '/Assemblies', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Создать Сборку
     * @param {Object} opts Optional parameters
     * @param {module:model/CreateOrUpdateAssemblyRequest} opts.createOrUpdateAssemblyRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/AssemblyDto}
     */
    assembliesPost(opts) {
      return this.assembliesPostWithHttpInfo(opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
