/**
 * kdepa-api
 * КДЭПА CRUD API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CreateOrUpdateDriveMarkRequest model module.
 * @module model/CreateOrUpdateDriveMarkRequest
 * @version 0.1.0
 */
class CreateOrUpdateDriveMarkRequest {
    /**
     * Constructs a new <code>CreateOrUpdateDriveMarkRequest</code>.
     * @alias module:model/CreateOrUpdateDriveMarkRequest
     */
    constructor() { 
        
        CreateOrUpdateDriveMarkRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CreateOrUpdateDriveMarkRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreateOrUpdateDriveMarkRequest} obj Optional instance to populate.
     * @return {module:model/CreateOrUpdateDriveMarkRequest} The populated <code>CreateOrUpdateDriveMarkRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateOrUpdateDriveMarkRequest();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('gearRatio')) {
                obj['gearRatio'] = ApiClient.convertToType(data['gearRatio'], 'Number');
            }
            if (data.hasOwnProperty('torque')) {
                obj['torque'] = ApiClient.convertToType(data['torque'], 'Number');
            }
            if (data.hasOwnProperty('rotationFrequency')) {
                obj['rotationFrequency'] = ApiClient.convertToType(data['rotationFrequency'], 'Number');
            }
            if (data.hasOwnProperty('efficiency')) {
                obj['efficiency'] = ApiClient.convertToType(data['efficiency'], 'Number');
            }
            if (data.hasOwnProperty('modification')) {
                obj['modification'] = ApiClient.convertToType(data['modification'], 'String');
            }
            if (data.hasOwnProperty('turnNumberMin')) {
                obj['turnNumberMin'] = ApiClient.convertToType(data['turnNumberMin'], 'Number');
            }
            if (data.hasOwnProperty('turnNumberMax')) {
                obj['turnNumberMax'] = ApiClient.convertToType(data['turnNumberMax'], 'Number');
            }
            if (data.hasOwnProperty('weight')) {
                obj['weight'] = ApiClient.convertToType(data['weight'], 'Number');
            }
            if (data.hasOwnProperty('serviceLife')) {
                obj['serviceLife'] = ApiClient.convertToType(data['serviceLife'], 'Number');
            }
            if (data.hasOwnProperty('assignedResource')) {
                obj['assignedResource'] = ApiClient.convertToType(data['assignedResource'], 'Number');
            }
            if (data.hasOwnProperty('timeToFailure')) {
                obj['timeToFailure'] = ApiClient.convertToType(data['timeToFailure'], 'Number');
            }
            if (data.hasOwnProperty('probabilityOfFailure')) {
                obj['probabilityOfFailure'] = ApiClient.convertToType(data['probabilityOfFailure'], 'Number');
            }
            if (data.hasOwnProperty('technicalUseCoeff')) {
                obj['technicalUseCoeff'] = ApiClient.convertToType(data['technicalUseCoeff'], 'Number');
            }
            if (data.hasOwnProperty('availabilityFactor')) {
                obj['availabilityFactor'] = ApiClient.convertToType(data['availabilityFactor'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CreateOrUpdateDriveMarkRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CreateOrUpdateDriveMarkRequest</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['modification'] && !(typeof data['modification'] === 'string' || data['modification'] instanceof String)) {
            throw new Error("Expected the field `modification` to be a primitive type in the JSON string but got " + data['modification']);
        }

        return true;
    }


}



/**
 * @member {String} name
 */
CreateOrUpdateDriveMarkRequest.prototype['name'] = undefined;

/**
 * @member {Number} gearRatio
 */
CreateOrUpdateDriveMarkRequest.prototype['gearRatio'] = undefined;

/**
 * @member {Number} torque
 */
CreateOrUpdateDriveMarkRequest.prototype['torque'] = undefined;

/**
 * @member {Number} rotationFrequency
 */
CreateOrUpdateDriveMarkRequest.prototype['rotationFrequency'] = undefined;

/**
 * @member {Number} efficiency
 */
CreateOrUpdateDriveMarkRequest.prototype['efficiency'] = undefined;

/**
 * @member {String} modification
 */
CreateOrUpdateDriveMarkRequest.prototype['modification'] = undefined;

/**
 * @member {Number} turnNumberMin
 */
CreateOrUpdateDriveMarkRequest.prototype['turnNumberMin'] = undefined;

/**
 * @member {Number} turnNumberMax
 */
CreateOrUpdateDriveMarkRequest.prototype['turnNumberMax'] = undefined;

/**
 * @member {Number} weight
 */
CreateOrUpdateDriveMarkRequest.prototype['weight'] = undefined;

/**
 * @member {Number} serviceLife
 */
CreateOrUpdateDriveMarkRequest.prototype['serviceLife'] = undefined;

/**
 * @member {Number} assignedResource
 */
CreateOrUpdateDriveMarkRequest.prototype['assignedResource'] = undefined;

/**
 * @member {Number} timeToFailure
 */
CreateOrUpdateDriveMarkRequest.prototype['timeToFailure'] = undefined;

/**
 * @member {Number} probabilityOfFailure
 */
CreateOrUpdateDriveMarkRequest.prototype['probabilityOfFailure'] = undefined;

/**
 * @member {Number} technicalUseCoeff
 */
CreateOrUpdateDriveMarkRequest.prototype['technicalUseCoeff'] = undefined;

/**
 * @member {Number} availabilityFactor
 */
CreateOrUpdateDriveMarkRequest.prototype['availabilityFactor'] = undefined;






export default CreateOrUpdateDriveMarkRequest;

