/**
 * kdepa-api
 * КДЭПА CRUD API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PositionDto model module.
 * @module model/PositionDto
 * @version 0.1.0
 */
class PositionDto {
    /**
     * Constructs a new <code>PositionDto</code>.
     * @alias module:model/PositionDto
     */
    constructor() { 
        
        PositionDto.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PositionDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PositionDto} obj Optional instance to populate.
     * @return {module:model/PositionDto} The populated <code>PositionDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PositionDto();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('systemId')) {
                obj['systemId'] = ApiClient.convertToType(data['systemId'], 'Number');
            }
            if (data.hasOwnProperty('system')) {
                obj['system'] = ApiClient.convertToType(data['system'], 'String');
            }
            if (data.hasOwnProperty('shopId')) {
                obj['shopId'] = ApiClient.convertToType(data['shopId'], 'Number');
            }
            if (data.hasOwnProperty('shop')) {
                obj['shop'] = ApiClient.convertToType(data['shop'], 'String');
            }
            if (data.hasOwnProperty('blockId')) {
                obj['blockId'] = ApiClient.convertToType(data['blockId'], 'Number');
            }
            if (data.hasOwnProperty('block')) {
                obj['block'] = ApiClient.convertToType(data['block'], 'Number');
            }
            if (data.hasOwnProperty('safetyClassId')) {
                obj['safetyClassId'] = ApiClient.convertToType(data['safetyClassId'], 'Number');
            }
            if (data.hasOwnProperty('safetyClass')) {
                obj['safetyClass'] = ApiClient.convertToType(data['safetyClass'], 'String');
            }
            if (data.hasOwnProperty('equipmentGroupId')) {
                obj['equipmentGroupId'] = ApiClient.convertToType(data['equipmentGroupId'], 'Number');
            }
            if (data.hasOwnProperty('equipmentGroup')) {
                obj['equipmentGroup'] = ApiClient.convertToType(data['equipmentGroup'], 'String');
            }
            if (data.hasOwnProperty('purpose')) {
                obj['purpose'] = ApiClient.convertToType(data['purpose'], 'String');
            }
            if (data.hasOwnProperty('operativeHeight')) {
                obj['operativeHeight'] = ApiClient.convertToType(data['operativeHeight'], 'String');
            }
            if (data.hasOwnProperty('marking')) {
                obj['marking'] = ApiClient.convertToType(data['marking'], 'String');
            }
            if (data.hasOwnProperty('cabinetId')) {
                obj['cabinetId'] = ApiClient.convertToType(data['cabinetId'], 'Number');
            }
            if (data.hasOwnProperty('cabinet')) {
                obj['cabinet'] = ApiClient.convertToType(data['cabinet'], 'String');
            }
            if (data.hasOwnProperty('seismicCategoryId')) {
                obj['seismicCategoryId'] = ApiClient.convertToType(data['seismicCategoryId'], 'Number');
            }
            if (data.hasOwnProperty('seismicCategory')) {
                obj['seismicCategory'] = ApiClient.convertToType(data['seismicCategory'], 'String');
            }
            if (data.hasOwnProperty('climaticExecutionId')) {
                obj['climaticExecutionId'] = ApiClient.convertToType(data['climaticExecutionId'], 'Number');
            }
            if (data.hasOwnProperty('climaticExecution')) {
                obj['climaticExecution'] = ApiClient.convertToType(data['climaticExecution'], 'String');
            }
            if (data.hasOwnProperty('atmosphereTypeId')) {
                obj['atmosphereTypeId'] = ApiClient.convertToType(data['atmosphereTypeId'], 'Number');
            }
            if (data.hasOwnProperty('atmosphereType')) {
                obj['atmosphereType'] = ApiClient.convertToType(data['atmosphereType'], 'String');
            }
            if (data.hasOwnProperty('mediumId')) {
                obj['mediumId'] = ApiClient.convertToType(data['mediumId'], 'Number');
            }
            if (data.hasOwnProperty('medium')) {
                obj['medium'] = ApiClient.convertToType(data['medium'], 'String');
            }
            if (data.hasOwnProperty('mediumPressure')) {
                obj['mediumPressure'] = ApiClient.convertToType(data['mediumPressure'], 'Number');
            }
            if (data.hasOwnProperty('mediumDensity')) {
                obj['mediumDensity'] = ApiClient.convertToType(data['mediumDensity'], 'Number');
            }
            if (data.hasOwnProperty('mediumTemperature')) {
                obj['mediumTemperature'] = ApiClient.convertToType(data['mediumTemperature'], 'Number');
            }
            if (data.hasOwnProperty('mediumHumidity')) {
                obj['mediumHumidity'] = ApiClient.convertToType(data['mediumHumidity'], 'Number');
            }
            if (data.hasOwnProperty('roomAirTemperature')) {
                obj['roomAirTemperature'] = ApiClient.convertToType(data['roomAirTemperature'], 'Number');
            }
            if (data.hasOwnProperty('roomAbsolutePressure')) {
                obj['roomAbsolutePressure'] = ApiClient.convertToType(data['roomAbsolutePressure'], 'Number');
            }
            if (data.hasOwnProperty('roomHumidity')) {
                obj['roomHumidity'] = ApiClient.convertToType(data['roomHumidity'], 'Number');
            }
            if (data.hasOwnProperty('roomDustLevel')) {
                obj['roomDustLevel'] = ApiClient.convertToType(data['roomDustLevel'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PositionDto</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PositionDto</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['system'] && !(typeof data['system'] === 'string' || data['system'] instanceof String)) {
            throw new Error("Expected the field `system` to be a primitive type in the JSON string but got " + data['system']);
        }
        // ensure the json data is a string
        if (data['shop'] && !(typeof data['shop'] === 'string' || data['shop'] instanceof String)) {
            throw new Error("Expected the field `shop` to be a primitive type in the JSON string but got " + data['shop']);
        }
        // ensure the json data is a string
        if (data['safetyClass'] && !(typeof data['safetyClass'] === 'string' || data['safetyClass'] instanceof String)) {
            throw new Error("Expected the field `safetyClass` to be a primitive type in the JSON string but got " + data['safetyClass']);
        }
        // ensure the json data is a string
        if (data['equipmentGroup'] && !(typeof data['equipmentGroup'] === 'string' || data['equipmentGroup'] instanceof String)) {
            throw new Error("Expected the field `equipmentGroup` to be a primitive type in the JSON string but got " + data['equipmentGroup']);
        }
        // ensure the json data is a string
        if (data['purpose'] && !(typeof data['purpose'] === 'string' || data['purpose'] instanceof String)) {
            throw new Error("Expected the field `purpose` to be a primitive type in the JSON string but got " + data['purpose']);
        }
        // ensure the json data is a string
        if (data['operativeHeight'] && !(typeof data['operativeHeight'] === 'string' || data['operativeHeight'] instanceof String)) {
            throw new Error("Expected the field `operativeHeight` to be a primitive type in the JSON string but got " + data['operativeHeight']);
        }
        // ensure the json data is a string
        if (data['marking'] && !(typeof data['marking'] === 'string' || data['marking'] instanceof String)) {
            throw new Error("Expected the field `marking` to be a primitive type in the JSON string but got " + data['marking']);
        }
        // ensure the json data is a string
        if (data['cabinet'] && !(typeof data['cabinet'] === 'string' || data['cabinet'] instanceof String)) {
            throw new Error("Expected the field `cabinet` to be a primitive type in the JSON string but got " + data['cabinet']);
        }
        // ensure the json data is a string
        if (data['seismicCategory'] && !(typeof data['seismicCategory'] === 'string' || data['seismicCategory'] instanceof String)) {
            throw new Error("Expected the field `seismicCategory` to be a primitive type in the JSON string but got " + data['seismicCategory']);
        }
        // ensure the json data is a string
        if (data['climaticExecution'] && !(typeof data['climaticExecution'] === 'string' || data['climaticExecution'] instanceof String)) {
            throw new Error("Expected the field `climaticExecution` to be a primitive type in the JSON string but got " + data['climaticExecution']);
        }
        // ensure the json data is a string
        if (data['atmosphereType'] && !(typeof data['atmosphereType'] === 'string' || data['atmosphereType'] instanceof String)) {
            throw new Error("Expected the field `atmosphereType` to be a primitive type in the JSON string but got " + data['atmosphereType']);
        }
        // ensure the json data is a string
        if (data['medium'] && !(typeof data['medium'] === 'string' || data['medium'] instanceof String)) {
            throw new Error("Expected the field `medium` to be a primitive type in the JSON string but got " + data['medium']);
        }
        // ensure the json data is a string
        if (data['roomDustLevel'] && !(typeof data['roomDustLevel'] === 'string' || data['roomDustLevel'] instanceof String)) {
            throw new Error("Expected the field `roomDustLevel` to be a primitive type in the JSON string but got " + data['roomDustLevel']);
        }

        return true;
    }


}



/**
 * @member {Number} id
 */
PositionDto.prototype['id'] = undefined;

/**
 * @member {String} name
 */
PositionDto.prototype['name'] = undefined;

/**
 * @member {Number} systemId
 */
PositionDto.prototype['systemId'] = undefined;

/**
 * @member {String} system
 */
PositionDto.prototype['system'] = undefined;

/**
 * @member {Number} shopId
 */
PositionDto.prototype['shopId'] = undefined;

/**
 * @member {String} shop
 */
PositionDto.prototype['shop'] = undefined;

/**
 * @member {Number} blockId
 */
PositionDto.prototype['blockId'] = undefined;

/**
 * @member {Number} block
 */
PositionDto.prototype['block'] = undefined;

/**
 * @member {Number} safetyClassId
 */
PositionDto.prototype['safetyClassId'] = undefined;

/**
 * @member {String} safetyClass
 */
PositionDto.prototype['safetyClass'] = undefined;

/**
 * @member {Number} equipmentGroupId
 */
PositionDto.prototype['equipmentGroupId'] = undefined;

/**
 * @member {String} equipmentGroup
 */
PositionDto.prototype['equipmentGroup'] = undefined;

/**
 * @member {String} purpose
 */
PositionDto.prototype['purpose'] = undefined;

/**
 * @member {String} operativeHeight
 */
PositionDto.prototype['operativeHeight'] = undefined;

/**
 * @member {String} marking
 */
PositionDto.prototype['marking'] = undefined;

/**
 * @member {Number} cabinetId
 */
PositionDto.prototype['cabinetId'] = undefined;

/**
 * @member {String} cabinet
 */
PositionDto.prototype['cabinet'] = undefined;

/**
 * @member {Number} seismicCategoryId
 */
PositionDto.prototype['seismicCategoryId'] = undefined;

/**
 * @member {String} seismicCategory
 */
PositionDto.prototype['seismicCategory'] = undefined;

/**
 * @member {Number} climaticExecutionId
 */
PositionDto.prototype['climaticExecutionId'] = undefined;

/**
 * @member {String} climaticExecution
 */
PositionDto.prototype['climaticExecution'] = undefined;

/**
 * @member {Number} atmosphereTypeId
 */
PositionDto.prototype['atmosphereTypeId'] = undefined;

/**
 * @member {String} atmosphereType
 */
PositionDto.prototype['atmosphereType'] = undefined;

/**
 * @member {Number} mediumId
 */
PositionDto.prototype['mediumId'] = undefined;

/**
 * @member {String} medium
 */
PositionDto.prototype['medium'] = undefined;

/**
 * @member {Number} mediumPressure
 */
PositionDto.prototype['mediumPressure'] = undefined;

/**
 * @member {Number} mediumDensity
 */
PositionDto.prototype['mediumDensity'] = undefined;

/**
 * @member {Number} mediumTemperature
 */
PositionDto.prototype['mediumTemperature'] = undefined;

/**
 * @member {Number} mediumHumidity
 */
PositionDto.prototype['mediumHumidity'] = undefined;

/**
 * @member {Number} roomAirTemperature
 */
PositionDto.prototype['roomAirTemperature'] = undefined;

/**
 * @member {Number} roomAbsolutePressure
 */
PositionDto.prototype['roomAbsolutePressure'] = undefined;

/**
 * @member {Number} roomHumidity
 */
PositionDto.prototype['roomHumidity'] = undefined;

/**
 * @member {String} roomDustLevel
 */
PositionDto.prototype['roomDustLevel'] = undefined;






export default PositionDto;

