/**
 * kdepa-api
 * КДЭПА CRUD API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The StatisticsDto model module.
 * @module model/StatisticsDto
 * @version 0.1.0
 */
class StatisticsDto {
    /**
     * Constructs a new <code>StatisticsDto</code>.
     * @alias module:model/StatisticsDto
     */
    constructor() { 
        
        StatisticsDto.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>StatisticsDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/StatisticsDto} obj Optional instance to populate.
     * @return {module:model/StatisticsDto} The populated <code>StatisticsDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new StatisticsDto();

            if (data.hasOwnProperty('hasInterval')) {
                obj['hasInterval'] = ApiClient.convertToType(data['hasInterval'], 'Boolean');
            }
            if (data.hasOwnProperty('lower')) {
                obj['lower'] = ApiClient.convertToType(data['lower'], 'Number');
            }
            if (data.hasOwnProperty('upper')) {
                obj['upper'] = ApiClient.convertToType(data['upper'], 'Number');
            }
            if (data.hasOwnProperty('p')) {
                obj['p'] = ApiClient.convertToType(data['p'], 'Number');
            }
            if (data.hasOwnProperty('fine')) {
                obj['fine'] = ApiClient.convertToType(data['fine'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>StatisticsDto</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>StatisticsDto</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * @member {Boolean} hasInterval
 */
StatisticsDto.prototype['hasInterval'] = undefined;

/**
 * @member {Number} lower
 */
StatisticsDto.prototype['lower'] = undefined;

/**
 * @member {Number} upper
 */
StatisticsDto.prototype['upper'] = undefined;

/**
 * @member {Number} p
 */
StatisticsDto.prototype['p'] = undefined;

/**
 * @member {Boolean} fine
 */
StatisticsDto.prototype['fine'] = undefined;






export default StatisticsDto;

