/**
 * kdepa-api
 * КДЭПА CRUD API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import CreateOrUpdateDriveRequest from '../model/CreateOrUpdateDriveRequest';
import DriveDto from '../model/DriveDto';
import DriveDtoDrivesQueryFilterDtoPagedItemsDto from '../model/DriveDtoDrivesQueryFilterDtoPagedItemsDto';

/**
* Drives service.
* @module api/DrivesApi
* @version 0.1.0
*/
export default class DrivesApi {

    /**
    * Constructs a new DrivesApi. 
    * @alias module:api/DrivesApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * Получить пагинированный список Приводов
     * @param {Object} opts Optional parameters
     * @param {Number} [pageSize = 10)] 
     * @param {Number} [pageIndex = 0)] 
     * @param {String} [sortBy] 
     * @param {Boolean} [ascending] 
     * @param {Array.<Number>} [ids] 
     * @param {Array.<Number>} [markIds] 
     * @param {Array.<Number>} [factoryIds] 
     * @param {String} [serialNumberSearchString] 
     * @param {Date} [madeDateFrom] 
     * @param {Date} [madeDateTo] 
     * @param {Date} [inUseDateFrom] 
     * @param {Date} [inUseDateTo] 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/DriveDtoDrivesQueryFilterDtoPagedItemsDto} and HTTP response
     */
    drivesGetWithHttpInfo(opts) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'pageSize': opts['pageSize'],
        'pageIndex': opts['pageIndex'],
        'SortBy': opts['sortBy'],
        'Ascending': opts['ascending'],
        'Ids': this.apiClient.buildCollectionParam(opts['ids'], 'multi'),
        'MarkIds': this.apiClient.buildCollectionParam(opts['markIds'], 'multi'),
        'FactoryIds': this.apiClient.buildCollectionParam(opts['factoryIds'], 'multi'),
        'SerialNumberSearchString': opts['serialNumberSearchString'],
        'MadeDateFrom': opts['madeDateFrom'],
        'MadeDateTo': opts['madeDateTo'],
        'InUseDateFrom': opts['inUseDateFrom'],
        'InUseDateTo': opts['inUseDateTo']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['text/plain', 'application/json', 'text/json'];
      let returnType = DriveDtoDrivesQueryFilterDtoPagedItemsDto;
      return this.apiClient.callApi(
        '/Drives', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Получить пагинированный список Приводов
     * @param {Object} opts Optional parameters
     * @param {Number} opts.pageSize  (default to 10)
     * @param {Number} opts.pageIndex  (default to 0)
     * @param {String} opts.sortBy 
     * @param {Boolean} opts.ascending 
     * @param {Array.<Number>} opts.ids 
     * @param {Array.<Number>} opts.markIds 
     * @param {Array.<Number>} opts.factoryIds 
     * @param {String} opts.serialNumberSearchString 
     * @param {Date} opts.madeDateFrom 
     * @param {Date} opts.madeDateTo 
     * @param {Date} opts.inUseDateFrom 
     * @param {Date} opts.inUseDateTo 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/DriveDtoDrivesQueryFilterDtoPagedItemsDto}
     */
    drivesGet(opts) {
      return this.drivesGetWithHttpInfo(opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Удалить Привод
     * @param {Number} id 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link String} and HTTP response
     */
    drivesIdDeleteWithHttpInfo(id) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling drivesIdDelete");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['text/plain', 'application/json', 'text/json'];
      let returnType = 'String';
      return this.apiClient.callApi(
        '/Drives/{id}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Удалить Привод
     * @param {Number} id 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link String}
     */
    drivesIdDelete(id) {
      return this.drivesIdDeleteWithHttpInfo(id)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Получить Привод по id
     * @param {Number} id 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/DriveDto} and HTTP response
     */
    drivesIdGetWithHttpInfo(id) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling drivesIdGet");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['text/plain', 'application/json', 'text/json'];
      let returnType = DriveDto;
      return this.apiClient.callApi(
        '/Drives/{id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Получить Привод по id
     * @param {Number} id 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/DriveDto}
     */
    drivesIdGet(id) {
      return this.drivesIdGetWithHttpInfo(id)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Обновить Привод
     * @param {Number} id 
     * @param {Object} opts Optional parameters
     * @param {module:model/CreateOrUpdateDriveRequest} [createOrUpdateDriveRequest] 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/DriveDto} and HTTP response
     */
    drivesIdPutWithHttpInfo(id, opts) {
      opts = opts || {};
      let postBody = opts['createOrUpdateDriveRequest'];
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling drivesIdPut");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json', 'text/json', 'application/*+json'];
      let accepts = ['text/plain', 'application/json', 'text/json'];
      let returnType = DriveDto;
      return this.apiClient.callApi(
        '/Drives/{id}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Обновить Привод
     * @param {Number} id 
     * @param {Object} opts Optional parameters
     * @param {module:model/CreateOrUpdateDriveRequest} opts.createOrUpdateDriveRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/DriveDto}
     */
    drivesIdPut(id, opts) {
      return this.drivesIdPutWithHttpInfo(id, opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Создать Привод
     * @param {Object} opts Optional parameters
     * @param {module:model/CreateOrUpdateDriveRequest} [createOrUpdateDriveRequest] 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/DriveDto} and HTTP response
     */
    drivesPostWithHttpInfo(opts) {
      opts = opts || {};
      let postBody = opts['createOrUpdateDriveRequest'];

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json', 'text/json', 'application/*+json'];
      let accepts = ['text/plain', 'application/json', 'text/json'];
      let returnType = DriveDto;
      return this.apiClient.callApi(
        '/Drives', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Создать Привод
     * @param {Object} opts Optional parameters
     * @param {module:model/CreateOrUpdateDriveRequest} opts.createOrUpdateDriveRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/DriveDto}
     */
    drivesPost(opts) {
      return this.drivesPostWithHttpInfo(opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
