/**
 * kdepa-api
 * КДЭПА CRUD API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.KdepaApi);
  }
}(this, function(expect, KdepaApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new KdepaApi.MotorDto();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('MotorDto', function() {
    it('should create an instance of MotorDto', function() {
      // uncomment below and update the code to test MotorDto
      //var instance = new KdepaApi.MotorDto();
      //expect(instance).to.be.a(KdepaApi.MotorDto);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new KdepaApi.MotorDto();
      //expect(instance).to.be();
    });

    it('should have the property markId (base name: "markId")', function() {
      // uncomment below and update the code to test the property markId
      //var instance = new KdepaApi.MotorDto();
      //expect(instance).to.be();
    });

    it('should have the property mark (base name: "mark")', function() {
      // uncomment below and update the code to test the property mark
      //var instance = new KdepaApi.MotorDto();
      //expect(instance).to.be();
    });

    it('should have the property factoryId (base name: "factoryId")', function() {
      // uncomment below and update the code to test the property factoryId
      //var instance = new KdepaApi.MotorDto();
      //expect(instance).to.be();
    });

    it('should have the property factory (base name: "factory")', function() {
      // uncomment below and update the code to test the property factory
      //var instance = new KdepaApi.MotorDto();
      //expect(instance).to.be();
    });

    it('should have the property serialNumber (base name: "serialNumber")', function() {
      // uncomment below and update the code to test the property serialNumber
      //var instance = new KdepaApi.MotorDto();
      //expect(instance).to.be();
    });

    it('should have the property madeDate (base name: "madeDate")', function() {
      // uncomment below and update the code to test the property madeDate
      //var instance = new KdepaApi.MotorDto();
      //expect(instance).to.be();
    });

    it('should have the property inUseDate (base name: "inUseDate")', function() {
      // uncomment below and update the code to test the property inUseDate
      //var instance = new KdepaApi.MotorDto();
      //expect(instance).to.be();
    });

    it('should have the property resistanceU (base name: "resistanceU")', function() {
      // uncomment below and update the code to test the property resistanceU
      //var instance = new KdepaApi.MotorDto();
      //expect(instance).to.be();
    });

    it('should have the property resistanceV (base name: "resistanceV")', function() {
      // uncomment below and update the code to test the property resistanceV
      //var instance = new KdepaApi.MotorDto();
      //expect(instance).to.be();
    });

    it('should have the property resistanceW (base name: "resistanceW")', function() {
      // uncomment below and update the code to test the property resistanceW
      //var instance = new KdepaApi.MotorDto();
      //expect(instance).to.be();
    });

  });

}));
