/**
 * kdepa-api
 * КДЭПА CRUD API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.KdepaApi);
  }
}(this, function(expect, KdepaApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new KdepaApi.UpdateChannelSubRequest();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('UpdateChannelSubRequest', function() {
    it('should create an instance of UpdateChannelSubRequest', function() {
      // uncomment below and update the code to test UpdateChannelSubRequest
      //var instance = new KdepaApi.UpdateChannelSubRequest();
      //expect(instance).to.be.a(KdepaApi.UpdateChannelSubRequest);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new KdepaApi.UpdateChannelSubRequest();
      //expect(instance).to.be();
    });

    it('should have the property surveyId (base name: "surveyId")', function() {
      // uncomment below and update the code to test the property surveyId
      //var instance = new KdepaApi.UpdateChannelSubRequest();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new KdepaApi.UpdateChannelSubRequest();
      //expect(instance).to.be();
    });

    it('should have the property sampleRate (base name: "sampleRate")', function() {
      // uncomment below and update the code to test the property sampleRate
      //var instance = new KdepaApi.UpdateChannelSubRequest();
      //expect(instance).to.be();
    });

    it('should have the property unit (base name: "unit")', function() {
      // uncomment below and update the code to test the property unit
      //var instance = new KdepaApi.UpdateChannelSubRequest();
      //expect(instance).to.be();
    });

    it('should have the property type (base name: "type")', function() {
      // uncomment below and update the code to test the property type
      //var instance = new KdepaApi.UpdateChannelSubRequest();
      //expect(instance).to.be();
    });

    it('should have the property sumCoeff (base name: "sumCoeff")', function() {
      // uncomment below and update the code to test the property sumCoeff
      //var instance = new KdepaApi.UpdateChannelSubRequest();
      //expect(instance).to.be();
    });

    it('should have the property devCoeff (base name: "devCoeff")', function() {
      // uncomment below and update the code to test the property devCoeff
      //var instance = new KdepaApi.UpdateChannelSubRequest();
      //expect(instance).to.be();
    });

    it('should have the property offsetFromZero (base name: "offsetFromZero")', function() {
      // uncomment below and update the code to test the property offsetFromZero
      //var instance = new KdepaApi.UpdateChannelSubRequest();
      //expect(instance).to.be();
    });

  });

}));
