/**
 * kdepa-api-middleware
 * КДЭПА CRUD API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import CreateStationDto from './model/CreateStationDto';
import SortDto from './model/SortDto';
import StationDto from './model/StationDto';
import StationDtoPaginatedItemsDto from './model/StationDtoPaginatedItemsDto';
import StationsApi from './api/StationsApi';


/**
* КДЭПА CRUD API.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var KdepaApiMiddleware = require('index'); // See note below*.
* var xxxSvc = new KdepaApiMiddleware.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new KdepaApiMiddleware.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new KdepaApiMiddleware.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new KdepaApiMiddleware.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 0.1.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The CreateStationDto model constructor.
     * @property {module:model/CreateStationDto}
     */
    CreateStationDto,

    /**
     * The SortDto model constructor.
     * @property {module:model/SortDto}
     */
    SortDto,

    /**
     * The StationDto model constructor.
     * @property {module:model/StationDto}
     */
    StationDto,

    /**
     * The StationDtoPaginatedItemsDto model constructor.
     * @property {module:model/StationDtoPaginatedItemsDto}
     */
    StationDtoPaginatedItemsDto,

    /**
    * The StationsApi service constructor.
    * @property {module:api/StationsApi}
    */
    StationsApi
};
