/**
 * КДЭПА CRUD
 * КДЭПА CRUD API
 *
 * The version of the OpenAPI document: v0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import ProblemDetails from './model/ProblemDetails';
import SimpleQueryFilter from './model/SimpleQueryFilter';
import SortDto from './model/SortDto';
import Station from './model/Station';
import StationPaginatedItemsViewModel from './model/StationPaginatedItemsViewModel';
import StationsApi from './api/StationsApi';


/**
* КДЭПА CRUD API.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var Crud = require('index'); // See note below*.
* var xxxSvc = new Crud.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new Crud.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new Crud.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new Crud.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version v0.1
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The ProblemDetails model constructor.
     * @property {module:model/ProblemDetails}
     */
    ProblemDetails,

    /**
     * The SimpleQueryFilter model constructor.
     * @property {module:model/SimpleQueryFilter}
     */
    SimpleQueryFilter,

    /**
     * The SortDto model constructor.
     * @property {module:model/SortDto}
     */
    SortDto,

    /**
     * The Station model constructor.
     * @property {module:model/Station}
     */
    Station,

    /**
     * The StationPaginatedItemsViewModel model constructor.
     * @property {module:model/StationPaginatedItemsViewModel}
     */
    StationPaginatedItemsViewModel,

    /**
    * The StationsApi service constructor.
    * @property {module:api/StationsApi}
    */
    StationsApi
};
