/**
 * kdepa-api
 * КДЭПА CRUD API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.KdepaApi);
  }
}(this, function(expect, KdepaApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new KdepaApi.PositionsApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('PositionsApi', function() {
    describe('positionsGet', function() {
      it('should call positionsGet successfully', function(done) {
        //uncomment below and update the code to test positionsGet
        //instance.positionsGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('positionsIdDelete', function() {
      it('should call positionsIdDelete successfully', function(done) {
        //uncomment below and update the code to test positionsIdDelete
        //instance.positionsIdDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('positionsIdExtendedGet', function() {
      it('should call positionsIdExtendedGet successfully', function(done) {
        //uncomment below and update the code to test positionsIdExtendedGet
        //instance.positionsIdExtendedGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('positionsIdGet', function() {
      it('should call positionsIdGet successfully', function(done) {
        //uncomment below and update the code to test positionsIdGet
        //instance.positionsIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('positionsIdPut', function() {
      it('should call positionsIdPut successfully', function(done) {
        //uncomment below and update the code to test positionsIdPut
        //instance.positionsIdPut(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('positionsPost', function() {
      it('should call positionsPost successfully', function(done) {
        //uncomment below and update the code to test positionsPost
        //instance.positionsPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
