/**
 * kdepa-api
 * КДЭПА CRUD API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.KdepaApi);
  }
}(this, function(expect, KdepaApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new KdepaApi.SurveysRawApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('SurveysRawApi', function() {
    describe('surveysRawGet', function() {
      it('should call surveysRawGet successfully', function(done) {
        //uncomment below and update the code to test surveysRawGet
        //instance.surveysRawGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('surveysRawGuidChannelsIndexGet', function() {
      it('should call surveysRawGuidChannelsIndexGet successfully', function(done) {
        //uncomment below and update the code to test surveysRawGuidChannelsIndexGet
        //instance.surveysRawGuidChannelsIndexGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('surveysRawGuidDelete', function() {
      it('should call surveysRawGuidDelete successfully', function(done) {
        //uncomment below and update the code to test surveysRawGuidDelete
        //instance.surveysRawGuidDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('surveysRawGuidGet', function() {
      it('should call surveysRawGuidGet successfully', function(done) {
        //uncomment below and update the code to test surveysRawGuidGet
        //instance.surveysRawGuidGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('surveysRawPost', function() {
      it('should call surveysRawPost successfully', function(done) {
        //uncomment below and update the code to test surveysRawPost
        //instance.surveysRawPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
