name: Create NPM Package on GitHub

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ main, master ]
  create:
    tags: ["v*.*.*"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'package/**/package-lock.json'

      - name: Install dependencies
        run: npm ci
        working-directory: ./package
      
      - name: Build package
        run: npm run build
        working-directory: ./package

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: package/dist/

  publish-package:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'create' && startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: package/dist/

      - name: Setup Node.js for publishing
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://npm.pkg.github.com'

      - name: Install dependencies
        run: npm ci
        working-directory: ./package

      - name: Configure npm for GitHub Packages
        run: |
            echo "@andrey-aka-skif:registry=https://npm.pkg.github.com" >> .npmrc
            echo "//npm.pkg.github.com/:_authToken=${{ secrets.GH_PACKAGES_TOKEN }}" >> .npmrc

      - name: Publish to GitHub Packages
        run: npm publish
        working-directory: ./package
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}
